apiVersion: v1
kind: Namespace
metadata:
  name: axiom-dev
  labels:
    environment: development
    app.kubernetes.io/name: axiom
---
apiVersion: v1
kind: Namespace
metadata:
  name: axiom-staging
  labels:
    environment: staging
    app.kubernetes.io/name: axiom
---
apiVersion: v1
kind: Namespace
metadata:
  name: axiom-prod
  labels:
    environment: production
    app.kubernetes.io/name: axiom
